/**
 *  @ngdoc  module
 *  @name   appMain
 *
 *  @description
 *  Моки для тестирования модуля appMain.
 **/

const ReposListMock = [
	{
		id: 1296269,
		owner: {
			login: "test-user",
			id: 1,
			avatar_url: "https://github.com/images/error/test-user_happy.gif",
			gravatar_id: "",
			url: "https://api.github.com/users/test-user",
			html_url: "https://github.com/test-user",
			followers_url: "https://api.github.com/users/test-user/followers",
			following_url: "https://api.github.com/users/test-user/following{/other_user}",
			gists_url: "https://api.github.com/users/test-user/gists{/gist_id}",
			starred_url: "https://api.github.com/users/test-user/starred{/owner}{/repo}",
			subscriptions_url: "https://api.github.com/users/test-user/subscriptions",
			organizations_url: "https://api.github.com/users/test-user/orgs",
			repos_url: "https://api.github.com/users/test-user/repos",
			events_url: "https://api.github.com/users/test-user/events{/privacy}",
			received_events_url: "https://api.github.com/users/test-user/received_events",
			type: "User",
			site_admin: false
		},
		name: "test-repo",
		full_name: "test-user/test-repo",
		description: "This your first repo!",
		private: false,
		fork: true,
		url: "https://api.github.com/repos/test-user/test-repo",
		html_url: "https://github.com/test-user/test-repo",
		archive_url: "http://api.github.com/repos/test-user/test-repo/{archive_format}{/ref}",
		assignees_url: "http://api.github.com/repos/test-user/test-repo/assignees{/user}",
		blobs_url: "http://api.github.com/repos/test-user/test-repo/git/blobs{/sha}",
		branches_url: "http://api.github.com/repos/test-user/test-repo/branches{/branch}",
		clone_url: "https://github.com/test-user/test-repo.git",
		collaborators_url: "http://api.github.com/repos/test-user/test-repo/collaborators{/collaborator}",
		comments_url: "http://api.github.com/repos/test-user/test-repo/comments{/number}",
		commits_url: "http://api.github.com/repos/test-user/test-repo/commits{/sha}",
		compare_url: "http://api.github.com/repos/test-user/test-repo/compare/{base}...{head}",
		contents_url: "http://api.github.com/repos/test-user/test-repo/contents/{+path}",
		contributors_url: "http://api.github.com/repos/test-user/test-repo/contributors",
		deployments_url: "http://api.github.com/repos/test-user/test-repo/deployments",
		downloads_url: "http://api.github.com/repos/test-user/test-repo/downloads",
		events_url: "http://api.github.com/repos/test-user/test-repo/events",
		forks_url: "http://api.github.com/repos/test-user/test-repo/forks",
		git_commits_url: "http://api.github.com/repos/test-user/test-repo/git/commits{/sha}",
		git_refs_url: "http://api.github.com/repos/test-user/test-repo/git/refs{/sha}",
		git_tags_url: "http://api.github.com/repos/test-user/test-repo/git/tags{/sha}",
		git_url: "git:github.com/test-user/test-repo.git",
		hooks_url: "http://api.github.com/repos/test-user/test-repo/hooks",
		issue_comment_url: "http://api.github.com/repos/test-user/test-repo/issues/comments{/number}",
		issue_events_url: "http://api.github.com/repos/test-user/test-repo/issues/events{/number}",
		issues_url: "http://api.github.com/repos/test-user/test-repo/issues{/number}",
		keys_url: "http://api.github.com/repos/test-user/test-repo/keys{/key_id}",
		labels_url: "http://api.github.com/repos/test-user/test-repo/labels{/name}",
		languages_url: "http://api.github.com/repos/test-user/test-repo/languages",
		merges_url: "http://api.github.com/repos/test-user/test-repo/merges",
		milestones_url: "http://api.github.com/repos/test-user/test-repo/milestones{/number}",
		mirror_url: "git:git.example.com/test-user/test-repo",
		notifications_url: "http://api.github.com/repos/test-user/test-repo/notifications{?since, all, participating}",
		pulls_url: "http://api.github.com/repos/test-user/test-repo/pulls{/number}",
		releases_url: "http://api.github.com/repos/test-user/test-repo/releases{/id}",
		ssh_url: "git@github.com:test-user/test-repo.git",
		stargazers_url: "http://api.github.com/repos/test-user/test-repo/stargazers",
		statuses_url: "http://api.github.com/repos/test-user/test-repo/statuses/{sha}",
		subscribers_url: "http://api.github.com/repos/test-user/test-repo/subscribers",
		subscription_url: "http://api.github.com/repos/test-user/test-repo/subscription",
		svn_url: "https://svn.github.com/test-user/test-repo",
		tags_url: "http://api.github.com/repos/test-user/test-repo/tags",
		teams_url: "http://api.github.com/repos/test-user/test-repo/teams",
		trees_url: "http://api.github.com/repos/test-user/test-repo/git/trees{/sha}",
		homepage: "https://github.com",
		language: null,
		forks_count: 9,
		stargazers_count: 80,
		watchers_count: 80,
		size: 108,
		default_branch: "master",
		open_issues_count: 1,
		has_issues: true,
		has_wiki: true,
		has_pages: false,
		has_downloads: true,
		pushed_at: "2011-01-26T19:06:43Z",
		created_at: "2011-01-26T19:01:12Z",
		updated_at: "2011-01-26T19:14:43Z",
		permissions: {
			admin: false,
			push: false,
			pull: true
		}
	}
];

const IssuesListMock = [
	{
		id: 1,
		url: "https://api.github.com/repos/test-user/test-repo/issues/1",
		repository_url: "https://api.github.com/repos/test-user/test-repo",
		labels_url: "https://api.github.com/repos/test-user/test-repo/issues/1347/labels{/name}",
		comments_url: "https://api.github.com/repos/test-user/test-repo/issues/1347/comments",
		events_url: "https://api.github.com/repos/test-user/test-repo/issues/1347/events",
		html_url: "https://github.com/test-user/test-repo/issues/1347",
		number: 1,
		state: "open",
		title: "Found a bug",
		body: "I'm having a problem with this.",
		user: {
			login: "test-user",
			id: 1,
			avatar_url: "https://github.com/images/error/test-user_happy.gif",
			gravatar_id: "",
			url: "https://api.github.com/users/test-user",
			html_url: "https://github.com/test-user",
			followers_url: "https://api.github.com/users/test-user/followers",
			following_url: "https://api.github.com/users/test-user/following{/other_user}",
			gists_url: "https://api.github.com/users/test-user/gists{/gist_id}",
			starred_url: "https://api.github.com/users/test-user/starred{/owner}{/repo}",
			subscriptions_url: "https://api.github.com/users/test-user/subscriptions",
			organizations_url: "https://api.github.com/users/test-user/orgs",
			repos_url: "https://api.github.com/users/test-user/repos",
			events_url: "https://api.github.com/users/test-user/events{/privacy}",
			received_events_url: "https://api.github.com/users/test-user/received_events",
			type: "User",
			site_admin: false
		},
		labels: [
			{
				url: "https://api.github.com/repos/test-user/test-repo/labels/bug",
				name: "bug",
				color: "f29513"
			}
		],
		assignee: {
			login: "test-user",
			id: 1,
			avatar_url: "https://github.com/images/error/test-user_happy.gif",
			gravatar_id: "",
			url: "https://api.github.com/users/test-user",
			html_url: "https://github.com/test-user",
			followers_url: "https://api.github.com/users/test-user/followers",
			following_url: "https://api.github.com/users/test-user/following{/other_user}",
			gists_url: "https://api.github.com/users/test-user/gists{/gist_id}",
			starred_url: "https://api.github.com/users/test-user/starred{/owner}{/repo}",
			subscriptions_url: "https://api.github.com/users/test-user/subscriptions",
			organizations_url: "https://api.github.com/users/test-user/orgs",
			repos_url: "https://api.github.com/users/test-user/repos",
			events_url: "https://api.github.com/users/test-user/events{/privacy}",
			received_events_url: "https://api.github.com/users/test-user/received_events",
			type: "User",
			site_admin: false
		},
		milestone: {
			url: "https://api.github.com/repos/test-user/test-repo/milestones/1",
			html_url: "https://github.com/test-user/test-repo/milestones/v1.0",
			labels_url: "https://api.github.com/repos/test-user/test-repo/milestones/1/labels",
			id: 1002604,
			number: 1,
			state: "open",
			title: "v1.0",
			description: "Tracking milestone for version 1.0",
			creator: {
				login: "test-user",
				id: 1,
				avatar_url: "https://github.com/images/error/test-user_happy.gif",
				gravatar_id: "",
				url: "https://api.github.com/users/test-user",
				html_url: "https://github.com/test-user",
				followers_url: "https://api.github.com/users/test-user/followers",
				following_url: "https://api.github.com/users/test-user/following{/other_user}",
				gists_url: "https://api.github.com/users/test-user/gists{/gist_id}",
				starred_url: "https://api.github.com/users/test-user/starred{/owner}{/repo}",
				subscriptions_url: "https://api.github.com/users/test-user/subscriptions",
				organizations_url: "https://api.github.com/users/test-user/orgs",
				repos_url: "https://api.github.com/users/test-user/repos",
				events_url: "https://api.github.com/users/test-user/events{/privacy}",
				received_events_url: "https://api.github.com/users/test-user/received_events",
				type: "User",
				site_admin: false
			},
			open_issues: 4,
			closed_issues: 8,
			created_at: "2011-04-10T20:09:31Z",
			updated_at: "2014-03-03T18:58:10Z",
			closed_at: "2013-02-12T13:22:01Z",
			due_on: "2012-10-09T23:39:01Z"
		},
		locked: false,
		comments: 0,
		pull_request: {
			url: "https://api.github.com/repos/test-user/test-repo/pulls/1347",
			html_url: "https://github.com/test-user/test-repo/pull/1347",
			diff_url: "https://github.com/test-user/test-repo/pull/1347.diff",
			patch_url: "https://github.com/test-user/test-repo/pull/1347.patch"
		},
		closed_at: null,
		created_at: "2011-04-22T13:33:48Z",
		updated_at: "2011-04-22T13:33:48Z"
	}
];

const IssueMock = {
	id: 1,
	url: "https://api.github.com/repos/test-user/test-repo/issues/1",
	repository_url: "https://api.github.com/repos/test-user/test-repo",
	labels_url: "https://api.github.com/repos/test-user/test-repo/issues/1347/labels{/name}",
	comments_url: "https://api.github.com/repos/test-user/test-repo/issues/1347/comments",
	events_url: "https://api.github.com/repos/test-user/test-repo/issues/1347/events",
	html_url: "https://github.com/test-user/test-repo/issues/1347",
	number: 1,
	state: "open",
	title: "Found a bug",
	body: "I'm having a problem with this.",
	user: {
		login: "test-user",
		id: 1,
		avatar_url: "https://github.com/images/error/test-user_happy.gif",
		gravatar_id: "",
		url: "https://api.github.com/users/test-user",
		html_url: "https://github.com/test-user",
		followers_url: "https://api.github.com/users/test-user/followers",
		following_url: "https://api.github.com/users/test-user/following{/other_user}",
		gists_url: "https://api.github.com/users/test-user/gists{/gist_id}",
		starred_url: "https://api.github.com/users/test-user/starred{/owner}{/repo}",
		subscriptions_url: "https://api.github.com/users/test-user/subscriptions",
		organizations_url: "https://api.github.com/users/test-user/orgs",
		repos_url: "https://api.github.com/users/test-user/repos",
		events_url: "https://api.github.com/users/test-user/events{/privacy}",
		received_events_url: "https://api.github.com/users/test-user/received_events",
		type: "User",
		site_admin: false
	},
	labels: [
		{
			url: "https://api.github.com/repos/test-user/test-repo/labels/bug",
			name: "bug",
			color: "f29513"
		}
	],
	assignee: {
		login: "test-user",
		id: 1,
		avatar_url: "https://github.com/images/error/test-user_happy.gif",
		gravatar_id: "",
		url: "https://api.github.com/users/test-user",
		html_url: "https://github.com/test-user",
		followers_url: "https://api.github.com/users/test-user/followers",
		following_url: "https://api.github.com/users/test-user/following{/other_user}",
		gists_url: "https://api.github.com/users/test-user/gists{/gist_id}",
		starred_url: "https://api.github.com/users/test-user/starred{/owner}{/repo}",
		subscriptions_url: "https://api.github.com/users/test-user/subscriptions",
		organizations_url: "https://api.github.com/users/test-user/orgs",
		repos_url: "https://api.github.com/users/test-user/repos",
		events_url: "https://api.github.com/users/test-user/events{/privacy}",
		received_events_url: "https://api.github.com/users/test-user/received_events",
		type: "User",
		site_admin: false
	},
	milestone: {
		url: "https://api.github.com/repos/test-user/test-repo/milestones/1",
		html_url: "https://github.com/test-user/test-repo/milestones/v1.0",
		labels_url: "https://api.github.com/repos/test-user/test-repo/milestones/1/labels",
		id: 1002604,
		number: 1,
		state: "open",
		title: "v1.0",
		description: "Tracking milestone for version 1.0",
		creator: {
			login: "test-user",
			id: 1,
			avatar_url: "https://github.com/images/error/test-user_happy.gif",
			gravatar_id: "",
			url: "https://api.github.com/users/test-user",
			html_url: "https://github.com/test-user",
			followers_url: "https://api.github.com/users/test-user/followers",
			following_url: "https://api.github.com/users/test-user/following{/other_user}",
			gists_url: "https://api.github.com/users/test-user/gists{/gist_id}",
			starred_url: "https://api.github.com/users/test-user/starred{/owner}{/repo}",
			subscriptions_url: "https://api.github.com/users/test-user/subscriptions",
			organizations_url: "https://api.github.com/users/test-user/orgs",
			repos_url: "https://api.github.com/users/test-user/repos",
			events_url: "https://api.github.com/users/test-user/events{/privacy}",
			received_events_url: "https://api.github.com/users/test-user/received_events",
			type: "User",
			site_admin: false
		},
		open_issues: 4,
		closed_issues: 8,
		created_at: "2011-04-10T20:09:31Z",
		updated_at: "2014-03-03T18:58:10Z",
		closed_at: "2013-02-12T13:22:01Z",
		due_on: "2012-10-09T23:39:01Z"
	},
	locked: false,
	comments: 0,
	pull_request: {
		url: "https://api.github.com/repos/test-user/test-repo/pulls/1347",
		html_url: "https://github.com/test-user/test-repo/pull/1347",
		diff_url: "https://github.com/test-user/test-repo/pull/1347.diff",
		patch_url: "https://github.com/test-user/test-repo/pull/1347.patch"
	},
	closed_at: null,
	created_at: "2011-04-22T13:33:48Z",
	updated_at: "2011-04-22T13:33:48Z"
}

export { ReposListMock, IssuesListMock, IssueMock };
